CREATE TABLE product (
    id int8 GENERATED BY
        DEFAULT AS IDENTITY,
        active boolean,
        description varchar(255),
        name varchar(50),
        image oid,
        price numeric(19, 2),
        stock numeric(19, 2),
        PRIMARY KEY (id)
);

CREATE TABLE product_product_type (
    product_id int8 NOT NULL,
    product_type_id int8 NOT NULL
);

CREATE TABLE product_type (
    id int8 GENERATED BY
        DEFAULT AS IDENTITY,
        description varchar(255),
        image oid,
        name varchar(50),
        PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS product_product_type
    ADD CONSTRAINT product_type_id_fk FOREIGN KEY (product_type_id) REFERENCES product_type;

ALTER TABLE IF EXISTS product_product_type
    ADD CONSTRAINT product_id_fk FOREIGN KEY (product_id) REFERENCES product;

