CREATE TABLE address (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    address_cep varchar(255) NOT NULL,
    address_city varchar(255) NOT NULL,
    address_complement varchar(255),
    address_district varchar(255) NOT NULL,
    address_number varchar(255) NOT NULL,
    address_reference_point varchar(255),
    address_state varchar(255) NOT NULL,
    address_street varchar(255) NOT NULL,
    PRIMARY KEY (id)
);
