CREATE TABLE cart (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    customer_email varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cart_item (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    quantity numeric(19, 2) NOT NULL,
    cart_id int8 NOT NULL,
    product_id int8 NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS cart
    ADD CONSTRAINT cart__customer_email_fk FOREIGN KEY (customer_email) REFERENCES customer;

ALTER TABLE IF EXISTS cart_item
    ADD CONSTRAINT cart_item__cart_fk FOREIGN KEY (cart_id) REFERENCES cart;

ALTER TABLE IF EXISTS cart_item
    ADD CONSTRAINT cart_item__product_fk FOREIGN KEY (product_id) REFERENCES product;